name: Build and deploy Python app to Azure Web App - CloudRecon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload backend folder for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8b9a7512-e07a-4f0c-be5f-b60eac42ec92 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_85fba696-c551-4178-b20c-c2b2b99b84fc }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_a9c73ede-7468-48f6-8f6d-8d2fa5f472bd }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CloudRecon'
          slot-name: 'Production'
          package: .


          
